language: scala

scala:
  - 2.12.11
  - 2.13.3

jdk:
  - openjdk11

before_script:
  - sudo chmod +x /usr/local/bin/sbt

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
